version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Mini_blog
    image: mini_blog_app
    volumes:
      - .:/var/www
    ports:
      - "6666:8080"
